In [1]:
import pandas as pd
import numpy as np

In [2]:
checkpoints_path = "https://github.com/RyanWangZf/BioBridge/raw/refs/heads/main/checkpoints/pytorch_model.bin"
checkpoints_dir = "checkpoints"

import os
if not os.path.exists(checkpoints_dir):
    os.makedirs(checkpoints_dir)

In [3]:
# import urllib.request
# urllib.request.urlretrieve(checkpoints_path, os.path.join(checkpoints_dir, "pytorch_model.bin"))

In [4]:
import os
os.environ["OPENAI_API_KEY"] = "XXX"
os.environ["NVDIA_API_KEY"] = "XXX"
import sys
sys.path.append("../../../")
from aiagents4pharma.talk2knowledgegraphs.models.biobridge.model import BioBridge

/home/awmulyadi/Repositories/temp/office2/AIAgents4Pharma/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
import torch

model = BioBridge(n_node=10, 
                  n_relation=18, 
                  proj_dim={7: 768, 0: 768, 5: 768, 1: 2560, 6: 512, 2: 768},
                  hidden_dim=768,
                  n_layer=6)
model.load_state_dict(torch.load(os.path.join(checkpoints_dir, "pytorch_model.bin")))

<All keys matched successfully>

In [6]:
@torch.no_grad()
def transformation(
    model: BioBridge, 
    x: torch.Tensor,
    src_type,
    tgt_type,
    rel_type
    ):
    """Inference based on the trained Bridge model to project raw embeddings to the target space.

    Args:
        model (BindingModel): the trained Bridge model.
        x (torch.Tensor): the raw embeddings to be projected.
        src_type (int): the type of the source space.
        tgt_type (int): the type of the target space.
        rel_type (int): the type of the relation.
    """
    if torch.cuda.is_available():
        x = x.to("cuda:0")
        model = model.to("cuda:0")
    
    model.eval()
    head_type_ids = torch.tensor([src_type] * len(x)).to(x.device)
    rel_type_ids = torch.tensor([rel_type] * len(x)).to(x.device)
    tail_type_ids = torch.tensor([tgt_type] * len(x)).to(x.device)
    output = model(
        head_emb=x,
        head_type_ids=head_type_ids,
        rel_type_ids=rel_type_ids,
        tail_type_ids=tail_type_ids,
    )
    return output['embeddings']


@torch.no_grad()
def project(
    model: BioBridge,
    x: torch.Tensor,
    src_type: int,
    ):
    """Project the raw embeddings to it's space with the modality-specific projection head"""
    if torch.cuda.is_available():
        x = x.to("cuda:0")
        model.to("cuda:0")
    
    model.eval()
    output = model.projection(
        node_emb=x,
        node_type_id=src_type,
    )
    return output

In [7]:
import sys
sys.path.append('../../..')
from aiagents4pharma.talk2knowledgegraphs.datasets.biobridge_primekg import BioBridgePrimeKG

# Define biobridge primekg data by providing a local directory where the data is stored
biobridge_data = BioBridgePrimeKG(primekg_dir="../../../../data/primekg/",
                                  local_dir="../../../../data/biobridge_primekg/")

# Invoke a method to load the data
biobridge_data.load_data()

# Get the node information of the BioBridge PrimeKG
biobridge_node_info = biobridge_data.get_node_info_dict()
biobridge_node_info.keys()

Loading PrimeKG dataset...
Loading nodes of PrimeKG dataset ...
../../../../data/primekg/primekg_nodes.tsv.gz already exists. Loading the data from the local directory.
Loading edges of PrimeKG dataset ...
../../../../data/primekg/primekg_edges.tsv.gz already exists. Loading the data from the local directory.
Loading data config file of BioBridgePrimeKG...
File data_config.json already exists in ../../../../data/biobridge_primekg/.
Building node embeddings...
Building full triplets...
Building train-test split...
Building negative triplets...


dict_keys(['gene/protein', 'molecular_function', 'cellular_component', 'biological_process', 'drug', 'disease'])

In [8]:
node_embeddings = biobridge_data.get_node_embeddings()

In [9]:
triplets = biobridge_data.get_primekg_triplets()
triplets.head()

head_index head_name head_source head_id  head_type  tail_index tail_name  \
0           0    PHYHIP        NCBI    9796          1        8889     KIF15   
1           1    GPANK1        NCBI    7918          1        2798     PNMA1   
2           2     ZRSR2        NCBI    8233          1        5646     TTC33   
3           3      NRF1        NCBI    4899          1       11592    MAN1B1   
4           4     PI4KA        NCBI    5297          1        2122     RGS20   

  tail_source tail_id  tail_type  display_relation         relation  
0        NCBI   56992          1                 3  protein_protein  
1        NCBI    9240          1                 3  protein_protein  
2        NCBI   23548          1                 3  protein_protein  
3        NCBI   11253          1                 3  protein_protein  
4        NCBI    8601          1                 3  protein_protein

### Gene/Protein --> Interactions With --> Cellular Component Retrieval

In [10]:
import pandas as pd
import numpy as np

cellcomp_protein_triplets = triplets[((triplets.head_type==1) & (triplets.tail_type==7))]
cellcomp_protein_triplets.head()

head_index head_name head_source head_id  head_type  tail_index  \
2858483        7097      A1BG        NCBI       1          1      126078   
2858484        6561      ACLY        NCBI      47          1      126078   
2858485        5420       AGL        NCBI     178          1      126078   
2858486        7661      ALAD        NCBI     210          1      126078   
2858487         652     ALDOA        NCBI     226          1      126078   

                            tail_name tail_source  tail_id  tail_type  \
2858483  ficolin-1-rich granule lumen          GO  1904813          7   
2858484  ficolin-1-rich granule lumen          GO  1904813          7   
2858485  ficolin-1-rich granule lumen          GO  1904813          7   
2858486  ficolin-1-rich granule lumen          GO  1904813          7   
2858487  ficolin-1-rich granule lumen          GO  1904813          7   

         display_relation          relation  
2858483                 2  cellcomp_protein  
2858484                 2  cellcomp_protein  
2858485                 2  cellcomp_protein  
2858486                 2  cellcomp_protein  
2858487                 2  cellcomp_protein

In [11]:
cellcomp_protein_triplets[cellcomp_protein_triplets.head_name == 'IL6']

head_index head_name head_source head_id  head_type  tail_index  \
2859040        1567       IL6        NCBI    3569          1      124245   
2863248        1567       IL6        NCBI    3569          1       56174   
2913339        1567       IL6        NCBI    3569          1       56117   
2929976        1567       IL6        NCBI    3569          1      124639   

                              tail_name tail_source tail_id  tail_type  \
2859040             extracellular space          GO    5615          7   
2863248            extracellular region          GO    5576          7   
2913339     endoplasmic reticulum lumen          GO    5788          7   
2929976  interleukin-6 receptor complex          GO    5896          7   

         display_relation          relation  
2859040                 2  cellcomp_protein  
2863248                 2  cellcomp_protein  
2913339                 2  cellcomp_protein  
2929976                 2  cellcomp_protein

In [13]:
x = torch.tensor(node_embeddings[1567]).unsqueeze(0)
x_transformed = transformation(model, x, 1, 7, 2)

In [14]:
cellcomp_as_tail_embeddings = torch.tensor([node_embeddings[i] for i in cellcomp_protein_triplets.tail_index.unique()])
# cellcomp_as_tail_embeddings = torch.tensor([node_embeddings[i] for i in [56241, 55840]])
cellcomp_as_tail_embeddings = project(model, cellcomp_as_tail_embeddings, 7)
cellcomp_as_tail_embeddings

tensor([[-0.0807, -0.2004,  0.2387,  ..., -0.0242, -0.0323, -0.1182],
        [ 0.0141, -0.0231, -0.0490,  ...,  0.0686,  0.0427, -0.0151],
        [-0.0069, -0.0176, -0.0296,  ...,  0.0992,  0.0151, -0.0302],
        ...,
        [ 0.0286,  0.0043,  0.1065,  ..., -0.1542, -0.0064, -0.0260],
        [ 0.0459, -0.0069,  0.0891,  ...,  0.0108,  0.1443,  0.0470],
        [-0.0481,  0.0733,  0.0166,  ..., -0.0518,  0.0415, -0.0794]],
       device='cuda:0')

In [15]:
sim_scores = torch.nn.CosineSimilarity(dim=-1)(x_transformed.cpu(), cellcomp_as_tail_embeddings.cpu())
sim_scores


tensor([ 0.3612,  0.8193,  0.4413,  ..., -0.3088, -0.4428, -0.1809])

In [18]:
cellcomp_protein_triplets[(cellcomp_protein_triplets.head_index == 1567)]

head_index head_name head_source head_id  head_type  tail_index  \
2859040        1567       IL6        NCBI    3569          1      124245   
2863248        1567       IL6        NCBI    3569          1       56174   
2913339        1567       IL6        NCBI    3569          1       56117   
2929976        1567       IL6        NCBI    3569          1      124639   

                              tail_name tail_source tail_id  tail_type  \
2859040             extracellular space          GO    5615          7   
2863248            extracellular region          GO    5576          7   
2913339     endoplasmic reticulum lumen          GO    5788          7   
2929976  interleukin-6 receptor complex          GO    5896          7   

         display_relation          relation  
2859040                 2  cellcomp_protein  
2863248                 2  cellcomp_protein  
2913339                 2  cellcomp_protein  
2929976                 2  cellcomp_protein

In [21]:
k_nodes = 10
sim_sorted = cellcomp_protein_triplets.tail_index.unique()[torch.argsort(sim_scores, descending=True)[:k_nodes]]
df_ = pd.DataFrame({
    "node_index": sim_sorted
})
df_.merge(biobridge_data.get_primekg().get_nodes(), on="node_index")

node_index                                 node_name node_source node_id  \
0      124245                       extracellular space          GO    5615   
1       56174                      extracellular region          GO    5576   
2      126196                     extracellular exosome          GO   70062   
3      124479                              cell surface          GO    9986   
4       56117               endoplasmic reticulum lumen          GO    5788   
5       55652                           lysosomal lumen          GO   43202   
6       56263                           plasma membrane          GO    5886   
7       56099  collagen-containing extracellular matrix          GO   62023   
8       55774                                  lysosome          GO    5764   
9       56241                                 cytoplasm          GO    5737   

            node_type  
0  cellular_component  
1  cellular_component  
2  cellular_component  
3  cellular_component  
4  cellular_component  
5  cellular_component  
6  cellular_component  
7  cellular_component  
8  cellular_component  
9  cellular_component

In [22]:
cellcomp_protein_triplets[(cellcomp_protein_triplets.head_index == 1567) & (cellcomp_protein_triplets.tail_index.isin(df_.node_index))]

head_index head_name head_source head_id  head_type  tail_index  \
2859040        1567       IL6        NCBI    3569          1      124245   
2863248        1567       IL6        NCBI    3569          1       56174   
2913339        1567       IL6        NCBI    3569          1       56117   

                           tail_name tail_source tail_id  tail_type  \
2859040          extracellular space          GO    5615          7   
2863248         extracellular region          GO    5576          7   
2913339  endoplasmic reticulum lumen          GO    5788          7   

         display_relation          relation  
2859040                 2  cellcomp_protein  
2863248                 2  cellcomp_protein  
2913339                 2  cellcomp_protein

### Gene/Protein --> Interactions With --> Biological Process

In [31]:
biop_protein_triplets = triplets[((triplets.head_type==1) & (triplets.tail_type==0))]
biop_protein_triplets.head()

head_index head_name head_source head_id  head_type  tail_index  \
2933235        7097      A1BG        NCBI       1          1      112487   
2933236        6931  SERPINA3        NCBI      12          1      112487   
2933237        1114      AOC1        NCBI      26          1      112487   
2933238        4852     ACAA1        NCBI      30          1      112487   
2933239        6561      ACLY        NCBI      47          1      112487   

                        tail_name tail_source tail_id  tail_type  \
2933235  neutrophil degranulation          GO   43312          0   
2933236  neutrophil degranulation          GO   43312          0   
2933237  neutrophil degranulation          GO   43312          0   
2933238  neutrophil degranulation          GO   43312          0   
2933239  neutrophil degranulation          GO   43312          0   

         display_relation            relation  
2933235                 2  bioprocess_protein  
2933236                 2  bioprocess_protein  
2933237                 2  bioprocess_protein  
2933238                 2  bioprocess_protein  
2933239                 2  bioprocess_protein

In [32]:
x = torch.tensor(node_embeddings[1567]).unsqueeze(0)
x_transformed = transformation(model, x, 1, 0, 2)

In [33]:
biop_as_tail_embeddings = torch.tensor([node_embeddings[i] for i in biop_protein_triplets.tail_index.unique()])
biop_as_tail_embeddings = project(model, biop_as_tail_embeddings, 0)
biop_as_tail_embeddings

tensor([[-0.0241, -0.0629, -0.0151,  ...,  0.0211, -0.0025, -0.0417],
        [ 0.0296, -0.0351, -0.0138,  ...,  0.0004,  0.0190, -0.0224],
        [-0.0776,  0.0672, -0.0461,  ...,  0.0166,  0.0414,  0.0134],
        ...,
        [-0.0183, -0.0412, -0.0489,  ..., -0.0369, -0.0756, -0.0308],
        [ 0.1868,  0.0523, -0.1393,  ..., -0.1839, -0.0607, -0.0005],
        [-0.0438,  0.0324, -0.0458,  ..., -0.0995,  0.0609,  0.0207]],
       device='cuda:0')

In [34]:
sim_scores = torch.nn.CosineSimilarity(dim=-1)(x_transformed.cpu(), biop_as_tail_embeddings.cpu())
sim_scores


tensor([ 0.4158,  0.3256,  0.2141,  ...,  0.0330, -0.2843,  0.0376])

In [35]:
biop_protein_triplets[(biop_protein_triplets.head_index == 1567)]

head_index head_name head_source head_id  head_type  tail_index  \
2934324        1567       IL6        NCBI    3569          1       53288   
2934454        1567       IL6        NCBI    3569          1       39999   
2937497        1567       IL6        NCBI    3569          1      101981   
2942054        1567       IL6        NCBI    3569          1       40924   
2943098        1567       IL6        NCBI    3569          1      112055   
...             ...       ...         ...     ...        ...         ...   
3054960        1567       IL6        NCBI    3569          1      100267   
3054961        1567       IL6        NCBI    3569          1       44690   
3054964        1567       IL6        NCBI    3569          1      112582   
3054971        1567       IL6        NCBI    3569          1      106339   
3054974        1567       IL6        NCBI    3569          1       46414   

                                                 tail_name tail_source  \
2934324                               acute-phase response          GO   
2934454                              inflammatory response          GO   
2937497            cellular response to lipopolysaccharide          GO   
2942054                         response to glucocorticoid          GO   
2943098             cellular response to hydrogen peroxide          GO   
...                                                    ...         ...   
3054960                                 glucagon secretion          GO   
3054961  regulation of vascular endothelial growth fact...          GO   
3054964                T-helper 17 cell lineage commitment          GO   
3054971    negative regulation of primary miRNA processing          GO   
3054974                   regulation of glucagon secretion          GO   

         tail_id  tail_type  display_relation            relation  
2934324     6953          0                 2  bioprocess_protein  
2934454     6954          0                 2  bioprocess_protein  
2937497    71222          0                 2  bioprocess_protein  
2942054    51384          0                 2  bioprocess_protein  
2943098    70301          0                 2  bioprocess_protein  
...          ...        ...               ...                 ...  
3054960    70091          0                 2  bioprocess_protein  
3054961    10574          0                 2  bioprocess_protein  
3054964    72540          0                 2  bioprocess_protein  
3054971  2000635          0                 2  bioprocess_protein  
3054974    70092          0                 2  bioprocess_protein  

[90 rows x 12 columns]

In [36]:
k_nodes = 10
sim_sorted = biop_protein_triplets.tail_index.unique()[torch.argsort(sim_scores, descending=False)[:k_nodes]]
df_ = pd.DataFrame({
    "node_index": sim_sorted
})
df_.merge(biobridge_data.get_primekg().get_nodes(), on="node_index")

node_index                                          node_name node_source  \
0      101027          UDP-N-acetylglucosamine catabolic process          GO   
1       41340          UDP-N-acetylglucosamine metabolic process          GO   
2      104011    UDP-N-acetylglucosamine transmembrane transport          GO   
3       48968          nicotinamide nucleotide metabolic process          GO   
4       53476                        allantoin catabolic process          GO   
5       44151  tRNA threonylcarbamoyladenosine metabolic process          GO   
6       41134              chondroitin sulfate metabolic process          GO   
7      113839          ventral trunk neural crest cell migration          GO   
8      103386             seminal vesicle epithelium development          GO   
9       40786       aromatic amino acid family metabolic process          GO   

   node_id           node_type  
0     6049  biological_process  
1     6047  biological_process  
2  1990569  biological_process  
3    46496  biological_process  
4      256  biological_process  
5    70525  biological_process  
6    30204  biological_process  
7    36486  biological_process  
8    61108  biological_process  
9     9072  biological_process

In [37]:
biop_protein_triplets[(biop_protein_triplets.head_index == 1567) & (biop_protein_triplets.tail_index.isin(df_.node_index))]

Empty DataFrame
Columns: [head_index, head_name, head_source, head_id, head_type, tail_index, tail_name, tail_source, tail_id, tail_type, display_relation, relation]
Index: []

### Gene/Protein --> Interactions With --> Molecular Function

In [38]:
molfunc_protein_triplets = triplets[((triplets.head_type==1) & (triplets.tail_type==5))]
molfunc_protein_triplets.head()

head_index head_name head_source head_id  head_type  tail_index  \
2791722        1048       A2M        NCBI       2          1       54035   
2791723         227     IL1R1        NCBI    3554          1       54035   
2791724        1654     IL1R2        NCBI    7850          1       54035   
2791725        4761      HAX1        NCBI   10456          1       54035   
2791726       10311    TRIM16        NCBI   10626          1       54035   

                     tail_name tail_source tail_id  tail_type  \
2791722  interleukin-1 binding          GO   19966          5   
2791723  interleukin-1 binding          GO   19966          5   
2791724  interleukin-1 binding          GO   19966          5   
2791725  interleukin-1 binding          GO   19966          5   
2791726  interleukin-1 binding          GO   19966          5   

         display_relation         relation  
2791722                 2  molfunc_protein  
2791723                 2  molfunc_protein  
2791724                 2  molfunc_protein  
2791725                 2  molfunc_protein  
2791726                 2  molfunc_protein

In [39]:
x = torch.tensor(node_embeddings[227]).unsqueeze(0)
x_transformed = transformation(model, x, 1, 5, 2)

In [40]:
molfunc_as_tail_embeddings = torch.tensor([node_embeddings[i] for i in molfunc_protein_triplets.tail_index.unique()])
molfunc_as_tail_embeddings = project(model, molfunc_as_tail_embeddings, 5)
molfunc_as_tail_embeddings

tensor([[-0.0707,  0.1322,  0.1445,  ...,  0.1249,  0.0293, -0.1103],
        [-0.1251,  0.1678, -0.0270,  ..., -0.0909,  0.1080, -0.0051],
        [-0.0665, -0.0465, -0.0862,  ..., -0.0213,  0.0450,  0.0295],
        ...,
        [ 0.0389,  0.1112,  0.0184,  ..., -0.0653,  0.0009, -0.1544],
        [-0.0268, -0.2351,  0.0653,  ..., -0.0287,  0.0123, -0.0026],
        [ 0.0962, -0.0665,  0.1969,  ...,  0.0391, -0.1009, -0.1000]],
       device='cuda:0')

In [41]:
sim_scores = torch.nn.CosineSimilarity(dim=-1)(x_transformed.cpu(), molfunc_as_tail_embeddings.cpu())
sim_scores


tensor([ 0.3567,  0.0533,  0.3069,  ..., -0.2987,  0.0435, -0.0659])

In [42]:
molfunc_protein_triplets[(molfunc_protein_triplets.head_index == 227)]

head_index head_name head_source head_id  head_type  tail_index  \
2791723         227     IL1R1        NCBI    3554          1       54035   
2792167         227     IL1R1        NCBI    3554          1       54671   
2794566         227     IL1R1        NCBI    3554          1       53699   
2830120         227     IL1R1        NCBI    3554          1       53920   
2842435         227     IL1R1        NCBI    3554          1      124184   
2842451         227     IL1R1        NCBI    3554          1      122627   
2848778         227     IL1R1        NCBI    3554          1      117422   
2851419         227     IL1R1        NCBI    3554          1       54343   
2851426         227     IL1R1        NCBI    3554          1      120880   

                                                 tail_name tail_source  \
2791723                              interleukin-1 binding          GO   
2792167                                   protease binding          GO   
2794566                                    protein binding          GO   
2830120          transmembrane signaling receptor activity          GO   
2842435    NAD+ nucleotidase, cyclic ADP-ribose generating          GO   
2842451                      NAD(P)+ nucleosidase activity          GO   
2848778    platelet-derived growth factor receptor binding          GO   
2851419                    interleukin-1 receptor activity          GO   
2851426  interleukin-1, type I, activating receptor act...          GO   

        tail_id  tail_type  display_relation         relation  
2791723   19966          5                 2  molfunc_protein  
2792167    2020          5                 2  molfunc_protein  
2794566    5515          5                 2  molfunc_protein  
2830120    4888          5                 2  molfunc_protein  
2842435   61809          5                 2  molfunc_protein  
2842451   50135          5                 2  molfunc_protein  
2848778    5161          5                 2  molfunc_protein  
2851419    4908          5                 2  molfunc_protein  
2851426    4909          5                 2  molfunc_protein

In [43]:
k_nodes = 10
sim_sorted = molfunc_protein_triplets.tail_index.unique()[torch.argsort(sim_scores, descending=True)[:k_nodes]]
df_ = pd.DataFrame({
    "node_index": sim_sorted
})
df_ = df_.merge(biobridge_data.get_primekg().get_nodes(), on="node_index")
df_

node_index                                        node_name node_source  \
0      124184  NAD+ nucleotidase, cyclic ADP-ribose generating          GO   
1       54387                      signaling receptor activity          GO   
2       55436                        identical protein binding          GO   
3       54621                       cytokine receptor activity          GO   
4       53920        transmembrane signaling receptor activity          GO   
5       55100                 interleukin-17 receptor activity          GO   
6      122627                    NAD(P)+ nucleosidase activity          GO   
7      124125                protein homodimerization activity          GO   
8       53699                                  protein binding          GO   
9       55479                       NAD+ nucleosidase activity          GO   

  node_id           node_type  
0   61809  molecular_function  
1   38023  molecular_function  
2   42802  molecular_function  
3    4896  molecular_function  
4    4888  molecular_function  
5   30368  molecular_function  
6   50135  molecular_function  
7   42803  molecular_function  
8    5515  molecular_function  
9    3953  molecular_function

In [44]:
molfunc_protein_triplets[(molfunc_protein_triplets.head_index == 227) & (molfunc_protein_triplets.tail_index.isin(df_.node_index))]

head_index head_name head_source head_id  head_type  tail_index  \
2794566         227     IL1R1        NCBI    3554          1       53699   
2830120         227     IL1R1        NCBI    3554          1       53920   
2842435         227     IL1R1        NCBI    3554          1      124184   
2842451         227     IL1R1        NCBI    3554          1      122627   

                                               tail_name tail_source tail_id  \
2794566                                  protein binding          GO    5515   
2830120        transmembrane signaling receptor activity          GO    4888   
2842435  NAD+ nucleotidase, cyclic ADP-ribose generating          GO   61809   
2842451                    NAD(P)+ nucleosidase activity          GO   50135   

         tail_type  display_relation         relation  
2794566          5                 2  molfunc_protein  
2830120          5                 2  molfunc_protein  
2842435          5                 2  molfunc_protein  
2842451          5                 2  molfunc_protein

### Protein --> Associated With --> Disease

In [45]:
rel_id_to_str_dict = dict((v,k) for k,v in biobridge_data.get_data_config()['relation_type'].items())
rel_id_to_str_dict

{0: 'expression present',
 1: 'synergistic interaction',
 2: 'interacts with',
 3: 'ppi',
 4: 'phenotype present',
 5: 'parent-child',
 6: 'associated with',
 7: 'side effect',
 8: 'contraindication',
 9: 'expression absent',
 10: 'target',
 11: 'indication',
 12: 'enzyme',
 13: 'transporter',
 14: 'off-label use',
 15: 'linked to',
 16: 'phenotype absent',
 17: 'carrier'}

In [46]:
protein_disease_triplets = triplets[((triplets.head_type==1) & (triplets.tail_type==2) & (triplets.display_relation==6))]
protein_disease_triplets.head()

head_index head_name head_source head_id  head_type  tail_index  \
2613785        7097      A1BG        NCBI       1          1       28313   
2613786        2174     ABCA1        NCBI      19          1       28313   
2613787        8038      ACHE        NCBI      43          1       28313   
2613788        5925      ACP1        NCBI      52          1       28313   
2613789         238      ACTB        NCBI      60          1       28313   

             tail_name    tail_source  \
2613785  schizophrenia  MONDO_grouped   
2613786  schizophrenia  MONDO_grouped   
2613787  schizophrenia  MONDO_grouped   
2613788  schizophrenia  MONDO_grouped   
2613789  schizophrenia  MONDO_grouped   

                                                   tail_id  tail_type  \
2613785  5090_13498_8414_10897_33312_10943_11552_14092_...          2   
2613786  5090_13498_8414_10897_33312_10943_11552_14092_...          2   
2613787  5090_13498_8414_10897_33312_10943_11552_14092_...          2   
2613788  5090_13498_8414_10897_33312_10943_11552_14092_...          2   
2613789  5090_13498_8414_10897_33312_10943_11552_14092_...          2   

         display_relation         relation  
2613785                 6  disease_protein  
2613786                 6  disease_protein  
2613787                 6  disease_protein  
2613788                 6  disease_protein  
2613789                 6  disease_protein

In [47]:
protein_disease_triplets[protein_disease_triplets.head_name == 'IL6']

head_index head_name head_source head_id  head_type  tail_index  \
2614065        1567       IL6        NCBI    3569          1       28313   
2616054        1567       IL6        NCBI    3569          1       27933   
2616055        1567       IL6        NCBI    3569          1       83840   
2616056        1567       IL6        NCBI    3569          1       37703   
2616621        1567       IL6        NCBI    3569          1       83760   
...             ...       ...         ...     ...        ...         ...   
2686214        1567       IL6        NCBI    3569          1       27848   
2686216        1567       IL6        NCBI    3569          1       32631   
2686217        1567       IL6        NCBI    3569          1       33450   
2686218        1567       IL6        NCBI    3569          1       32589   
2691649        1567       IL6        NCBI    3569          1       33605   

                                        tail_name    tail_source  \
2614065                             schizophrenia  MONDO_grouped   
2616054                          anxiety disorder  MONDO_grouped   
2616055                       unipolar depression          MONDO   
2616056                         neurotic disorder          MONDO   
2616621                        dysthymic disorder          MONDO   
...                                           ...            ...   
2686214  arteriovenous malformations of the brain          MONDO   
2686216                         Castleman disease          MONDO   
2686217                            Kimura disease          MONDO   
2686218                Kaposi's sarcoma (disease)          MONDO   
2691649                      hypotensive disorder          MONDO   

                                                   tail_id  tail_type  \
2614065  5090_13498_8414_10897_33312_10943_11552_14092_...          2   
2616054  8187_2050_5618_5451_5371_100081_5383_1942_1098...          2   
2616055                                               5263          2   
2616056                                               5379          2   
2616621                                               1442          2   
...                                                    ...        ...   
2686214                                               7154          2   
2686216                                              15564          2   
2686217                                              18830          2   
2686218                                               5055          2   
2691649                                               5468          2   

         display_relation         relation  
2614065                 6  disease_protein  
2616054                 6  disease_protein  
2616055                 6  disease_protein  
2616056                 6  disease_protein  
2616621                 6  disease_protein  
...                   ...              ...  
2686214                 6  disease_protein  
2686216                 6  disease_protein  
2686217                 6  disease_protein  
2686218                 6  disease_protein  
2691649                 6  disease_protein  

[208 rows x 12 columns]

In [48]:
x = torch.tensor(node_embeddings[1567]).unsqueeze(0)
x_transformed = transformation(model, x, 1, 2, 6)

In [49]:
disease_as_tail_embeddings = torch.tensor([node_embeddings[i] for i in protein_disease_triplets.tail_index.unique()])
disease_as_tail_embeddings = project(model, disease_as_tail_embeddings, 2)
disease_as_tail_embeddings

/tmp/ipykernel_279101/4200249845.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:275.)
  disease_as_tail_embeddings = torch.tensor([node_embeddings[i] for i in protein_disease_triplets.tail_index.unique()])


tensor([[ 0.0253,  0.0084, -0.0078,  ...,  0.0232,  0.0047, -0.0244],
        [ 0.0379,  0.0670, -0.0542,  ...,  0.0828,  0.0433, -0.0453],
        [ 0.0105,  0.0471, -0.0431,  ...,  0.0377,  0.0832, -0.0056],
        ...,
        [ 0.0429,  0.2275, -0.0458,  ...,  0.0957,  0.1318, -0.0151],
        [ 0.0318,  0.0114, -0.0764,  ...,  0.0408,  0.0470, -0.0107],
        [ 0.1283, -0.1426,  0.0293,  ...,  0.1421, -0.1253,  0.0153]],
       device='cuda:0')

In [50]:
sim_scores = torch.nn.CosineSimilarity(dim=-1)(x_transformed.cpu(), disease_as_tail_embeddings.cpu())
sim_scores


tensor([0.6842, 0.4190, 0.1399,  ..., 0.2393, 0.1273, 0.0979])

In [53]:
protein_disease_triplets[(protein_disease_triplets.head_index == 1567)]

head_index head_name head_source head_id  head_type  tail_index  \
2614065        1567       IL6        NCBI    3569          1       28313   
2616054        1567       IL6        NCBI    3569          1       27933   
2616055        1567       IL6        NCBI    3569          1       83840   
2616056        1567       IL6        NCBI    3569          1       37703   
2616621        1567       IL6        NCBI    3569          1       83760   
...             ...       ...         ...     ...        ...         ...   
2686214        1567       IL6        NCBI    3569          1       27848   
2686216        1567       IL6        NCBI    3569          1       32631   
2686217        1567       IL6        NCBI    3569          1       33450   
2686218        1567       IL6        NCBI    3569          1       32589   
2691649        1567       IL6        NCBI    3569          1       33605   

                                        tail_name    tail_source  \
2614065                             schizophrenia  MONDO_grouped   
2616054                          anxiety disorder  MONDO_grouped   
2616055                       unipolar depression          MONDO   
2616056                         neurotic disorder          MONDO   
2616621                        dysthymic disorder          MONDO   
...                                           ...            ...   
2686214  arteriovenous malformations of the brain          MONDO   
2686216                         Castleman disease          MONDO   
2686217                            Kimura disease          MONDO   
2686218                Kaposi's sarcoma (disease)          MONDO   
2691649                      hypotensive disorder          MONDO   

                                                   tail_id  tail_type  \
2614065  5090_13498_8414_10897_33312_10943_11552_14092_...          2   
2616054  8187_2050_5618_5451_5371_100081_5383_1942_1098...          2   
2616055                                               5263          2   
2616056                                               5379          2   
2616621                                               1442          2   
...                                                    ...        ...   
2686214                                               7154          2   
2686216                                              15564          2   
2686217                                              18830          2   
2686218                                               5055          2   
2691649                                               5468          2   

         display_relation         relation  
2614065                 6  disease_protein  
2616054                 6  disease_protein  
2616055                 6  disease_protein  
2616056                 6  disease_protein  
2616621                 6  disease_protein  
...                   ...              ...  
2686214                 6  disease_protein  
2686216                 6  disease_protein  
2686217                 6  disease_protein  
2686218                 6  disease_protein  
2691649                 6  disease_protein  

[208 rows x 12 columns]

In [51]:
k_nodes = 10
sim_sorted = protein_disease_triplets.tail_index.unique()[torch.argsort(sim_scores, descending=True)[:k_nodes]]
df_ = pd.DataFrame({
    "node_index": sim_sorted
})
df_ = df_.merge(biobridge_data.get_primekg().get_nodes(), on="node_index")
df_

node_index                                          node_name  \
0       32617          hereditary breast ovarian cancer syndrome   
1       29646                           hepatocellular carcinoma   
2       35963                                 prostate carcinoma   
3       36691                                      breast cancer   
4       28313                                      schizophrenia   
5       28347                        hereditary breast carcinoma   
6       36634                                       liver cancer   
7       30826                        familial prostate carcinoma   
8       31116                                        lung cancer   
9       36999  adenocarcinoma of liver and intrahepatic bilia...   

     node_source                                            node_id node_type  
0          MONDO                                               3582   disease  
1  MONDO_grouped                              7256_18902_16216_3243   disease  
2          MONDO                                               5159   disease  
3          MONDO                                               7254   disease  
4  MONDO_grouped  5090_13498_8414_10897_33312_10943_11552_14092_...   disease  
5          MONDO                                              16419   disease  
6          MONDO                                               2691   disease  
7          MONDO                                              23122   disease  
8          MONDO                                               8903   disease  
9          MONDO                                              18532   disease

In [52]:
protein_disease_triplets[(protein_disease_triplets.head_index == 1567) & (protein_disease_triplets.tail_index.isin(df_.node_index))]

head_index head_name head_source head_id  head_type  tail_index  \
2614065        1567       IL6        NCBI    3569          1       28313   
2617303        1567       IL6        NCBI    3569          1       31116   
2618686        1567       IL6        NCBI    3569          1       29646   
2618687        1567       IL6        NCBI    3569          1       36634   
2618690        1567       IL6        NCBI    3569          1       36999   
2622616        1567       IL6        NCBI    3569          1       30826   
2622617        1567       IL6        NCBI    3569          1       35963   
2625489        1567       IL6        NCBI    3569          1       36691   
2625490        1567       IL6        NCBI    3569          1       28347   
2625492        1567       IL6        NCBI    3569          1       32617   

                                                 tail_name    tail_source  \
2614065                                      schizophrenia  MONDO_grouped   
2617303                                        lung cancer          MONDO   
2618686                           hepatocellular carcinoma  MONDO_grouped   
2618687                                       liver cancer          MONDO   
2618690  adenocarcinoma of liver and intrahepatic bilia...          MONDO   
2622616                        familial prostate carcinoma          MONDO   
2622617                                 prostate carcinoma          MONDO   
2625489                                      breast cancer          MONDO   
2625490                        hereditary breast carcinoma          MONDO   
2625492          hereditary breast ovarian cancer syndrome          MONDO   

                                                   tail_id  tail_type  \
2614065  5090_13498_8414_10897_33312_10943_11552_14092_...          2   
2617303                                               8903          2   
2618686                              7256_18902_16216_3243          2   
2618687                                               2691          2   
2618690                                              18532          2   
2622616                                              23122          2   
2622617                                               5159          2   
2625489                                               7254          2   
2625490                                              16419          2   
2625492                                               3582          2   

         display_relation         relation  
2614065                 6  disease_protein  
2617303                 6  disease_protein  
2618686                 6  disease_protein  
2618687                 6  disease_protein  
2618690                 6  disease_protein  
2622616                 6  disease_protein  
2622617                 6  disease_protein  
2625489                 6  disease_protein  
2625490                 6  disease_protein  
2625492                 6  disease_protein

### Drug --> target --> Protein

In [54]:
drug_protein_triplets = triplets[((triplets.head_type==6) & (triplets.tail_type==1) & (triplets.display_relation==10))]
drug_protein_triplets.head()

head_index            head_name head_source  head_id  head_type  \
320478       15906  Pyridoxal phosphate    DrugBank  DB00114          6   
320479       15907            Histidine    DrugBank  DB00117          6   
320480       15908        Glutamic acid    DrugBank  DB00142          6   
320481       15909      N-Acetyl-Serine    DrugBank  DB02340          6   
320482       15912             Arginine    DrugBank  DB00125          6   

        tail_index tail_name tail_source tail_id  tail_type  display_relation  \
320478       13174       HDC        NCBI    3067          1                10   
320479       13174       HDC        NCBI    3067          1                10   
320480       13982      GLS2        NCBI   27165          1                10   
320481         476     F13A1        NCBI    2162          1                10   
320482         373      NOS2        NCBI    4843          1                10   

            relation  
320478  drug_protein  
320479  drug_protein  
320480  drug_protein  
320481  drug_protein  
320482  drug_protein

In [55]:
drug_protein_triplets[drug_protein_triplets.head_name == 'VX-702']

head_index head_name head_source  head_id  head_type  tail_index  \
325600       17590    VX-702    DrugBank  DB05470          6        2329   
327092       17590    VX-702    DrugBank  DB05470          6        1567   
327601       17590    VX-702    DrugBank  DB05470          6         197   
327756       17590    VX-702    DrugBank  DB05470          6        1004   

       tail_name tail_source tail_id  tail_type  display_relation  \
325600       TNF        NCBI    7124          1                10   
327092       IL6        NCBI    3569          1                10   
327601    MAPK14        NCBI    1432          1                10   
327756      IL1B        NCBI    3553          1                10   

            relation  
325600  drug_protein  
327092  drug_protein  
327601  drug_protein  
327756  drug_protein

In [56]:
x = torch.tensor(node_embeddings[17590]).unsqueeze(0)
x_transformed = transformation(model, x, 6, 1, 10)

In [57]:
protein_as_tail_embeddings = torch.tensor([node_embeddings[i] for i in drug_protein_triplets.tail_index.unique()])
protein_as_tail_embeddings = project(model, protein_as_tail_embeddings, 1)
protein_as_tail_embeddings

tensor([[-0.0190,  0.0135, -0.0154,  ...,  0.0074,  0.0060, -0.0069],
        [ 0.0280,  0.0027, -0.0253,  ...,  0.0250, -0.0447,  0.0160],
        [ 0.0239,  0.0142, -0.0741,  ...,  0.0064,  0.0252, -0.0375],
        ...,
        [ 0.0937, -0.0517, -0.0641,  ..., -0.0124,  0.0872, -0.0445],
        [-0.0223, -0.0520, -0.0490,  ..., -0.0019,  0.0135,  0.0072],
        [-0.0574,  0.0115, -0.0159,  ..., -0.0164, -0.0439,  0.0058]],
       device='cuda:0')

In [58]:
sim_scores = torch.nn.CosineSimilarity(dim=-1)(x_transformed.cpu(), protein_as_tail_embeddings.cpu())
sim_scores


tensor([0.0406, 0.1026, 0.1759,  ..., 0.1038, 0.2429, 0.1229])

In [59]:
k_nodes = 10
sim_sorted = drug_protein_triplets.tail_index.unique()[torch.argsort(sim_scores, descending=True)[:k_nodes]]
df_ = pd.DataFrame({
    "node_index": sim_sorted
})
df_ = df_.merge(biobridge_data.get_primekg().get_nodes(), on="node_index")
df_

node_index node_name node_source node_id     node_type
0        1004      IL1B        NCBI    3553  gene/protein
1        1567       IL6        NCBI    3569  gene/protein
2        2329       TNF        NCBI    7124  gene/protein
3         373      NOS2        NCBI    4843  gene/protein
4        3495      IFNG        NCBI    3458  gene/protein
5        4425     PTGS2        NCBI    5743  gene/protein
6        4959      SOD2        NCBI    6648  gene/protein
7        9031     PTGS1        NCBI    5742  gene/protein
8        2617       IL2        NCBI    3558  gene/protein
9        4497      NOS3        NCBI    4846  gene/protein

In [60]:
drug_protein_triplets[(drug_protein_triplets.head_index == 17590) & (drug_protein_triplets.tail_index.isin(df_.node_index))]

head_index head_name head_source  head_id  head_type  tail_index  \
325600       17590    VX-702    DrugBank  DB05470          6        2329   
327092       17590    VX-702    DrugBank  DB05470          6        1567   
327756       17590    VX-702    DrugBank  DB05470          6        1004   

       tail_name tail_source tail_id  tail_type  display_relation  \
325600       TNF        NCBI    7124          1                10   
327092       IL6        NCBI    3569          1                10   
327756      IL1B        NCBI    3553          1                10   

            relation  
325600  drug_protein  
327092  drug_protein  
327756  drug_protein

In [61]:
triplets[(triplets.tail_index == 17590)]

head_index head_name head_source head_id  head_type  tail_index  \
3395156        2329       TNF        NCBI    7124          1       17590   
3396648        1567       IL6        NCBI    3569          1       17590   
3397157         197    MAPK14        NCBI    1432          1       17590   
3397312        1004      IL1B        NCBI    3553          1       17590   

        tail_name tail_source  tail_id  tail_type  display_relation  \
3395156    VX-702    DrugBank  DB05470          6                10   
3396648    VX-702    DrugBank  DB05470          6                10   
3397157    VX-702    DrugBank  DB05470          6                10   
3397312    VX-702    DrugBank  DB05470          6                10   

             relation  
3395156  drug_protein  
3396648  drug_protein  
3397157  drug_protein  
3397312  drug_protein

### Drug --> indication --> Disease

In [62]:
disease_drug_triplets = triplets[((triplets.head_type==6) & (triplets.tail_type==2) & (triplets.relation == 'indication'))]
disease_drug_triplets.head()

head_index   head_name head_source  head_id  head_type  tail_index  \
338350       16687  Fosinopril    DrugBank  DB00492          6       33577   
338351       16687  Fosinopril    DrugBank  DB00492          6       36035   
338382       20297   Imidapril    DrugBank  DB11783          6       33577   
338383       20297   Imidapril    DrugBank  DB11783          6       36035   
338386       16693  Cilazapril    DrugBank  DB01340          6       33577   

                    tail_name    tail_source                      tail_id  \
338350  hypertensive disorder          MONDO                         5044   
338351           hypertension  MONDO_grouped  1200_1134_15512_5080_100078   
338382  hypertensive disorder          MONDO                         5044   
338383           hypertension  MONDO_grouped  1200_1134_15512_5080_100078   
338386  hypertensive disorder          MONDO                         5044   

        tail_type  display_relation    relation  
338350          2                11  indication  
338351          2                11  indication  
338382          2                11  indication  
338383          2                11  indication  
338386          2                11  indication

In [63]:
x = torch.tensor(node_embeddings[15876]).unsqueeze(0)
x_transformed = transformation(model, x, 6, 2, 11)

In [64]:
disease_as_tail_embeddings = torch.tensor([node_embeddings[i] for i in disease_drug_triplets.tail_index.unique()])
disease_as_tail_embeddings = project(model, disease_as_tail_embeddings, 2)
disease_as_tail_embeddings

tensor([[ 0.0409,  0.0292, -0.0421,  ...,  0.0431,  0.0146, -0.0288],
        [ 0.0611,  0.0414, -0.0743,  ...,  0.0438,  0.0159,  0.0148],
        [-0.0644, -0.0216,  0.0536,  ...,  0.0428,  0.0860, -0.0244],
        ...,
        [ 0.0692,  0.0380, -0.0210,  ..., -0.0021,  0.0120, -0.0779],
        [-0.1167, -0.1835, -0.0063,  ..., -0.1303,  0.0858,  0.0656],
        [ 0.1024, -0.0349,  0.0101,  ..., -0.1269, -0.1475, -0.0919]],
       device='cuda:0')

In [65]:
sim_scores = torch.nn.CosineSimilarity(dim=-1)(x_transformed.cpu(), disease_as_tail_embeddings.cpu())
sim_scores


tensor([ 0.0512,  0.0664, -0.0638,  ...,  0.1381,  0.0153,  0.1727])

In [66]:
disease_drug_triplets[(disease_drug_triplets.head_index == 15876)]

head_index   head_name head_source  head_id  head_type  tail_index  \
364546       15876  Mesalazine    DrugBank  DB00244          6       37785   
364547       15876  Mesalazine    DrugBank  DB00244          6       28158   
372669       15876  Mesalazine    DrugBank  DB00244          6       83959   

                           tail_name    tail_source  \
364546  ulcerative colitis (disease)          MONDO   
364547    inflammatory bowel disease  MONDO_grouped   
372669  ulcerative proctosigmoiditis          MONDO   

                                                  tail_id  tail_type  \
364546                                               5101          2   
364547  9960_12845_33643_11471_12831_12875_12941_13153...          2   
372669                                               7005          2   

        display_relation    relation  
364546                11  indication  
364547                11  indication  
372669                11  indication

In [67]:
k_nodes = 10
sim_sorted = disease_drug_triplets.tail_index.unique()[torch.argsort(sim_scores, descending=True)[:k_nodes]]
df_ = pd.DataFrame({
    "node_index": sim_sorted
})
df_ = df_.merge(biobridge_data.get_primekg().get_nodes(), on="node_index")
df_

node_index                      node_name    node_source  \
0       36209                    arthropathy          MONDO   
1       29273  osteoarthritis susceptibility  MONDO_grouped   
2       29078           rheumatoid arthritis          MONDO   
3       33609                 osteoarthritis  MONDO_grouped   
4       28158     inflammatory bowel disease  MONDO_grouped   
5       36265            spondyloarthropathy  MONDO_grouped   
6       37785   ulcerative colitis (disease)          MONDO   
7       83770                Crohn's colitis          MONDO   
8       32325  juvenile idiopathic arthritis  MONDO_grouped   
9       37784                  Crohn disease  MONDO_grouped   

                                             node_id node_type  
0                                               6816   disease  
1                  8143_7704_11923_12893_12894_12568   disease  
2                                               8383   disease  
3                      5178_6629_5416_6630_6631_6632   disease  
4  9960_12845_33643_11471_12831_12875_12941_13153...   disease  
5                                         5095_43377   disease  
6                                               5101   disease  
7                                               5532   disease  
8                                        11429_19433   disease  
9                                          5011_5535   disease

In [68]:
disease_drug_triplets[(disease_drug_triplets.head_index == 15876) & (disease_drug_triplets.tail_index.isin(df_.node_index))]

head_index   head_name head_source  head_id  head_type  tail_index  \
364546       15876  Mesalazine    DrugBank  DB00244          6       37785   
364547       15876  Mesalazine    DrugBank  DB00244          6       28158   

                           tail_name    tail_source  \
364546  ulcerative colitis (disease)          MONDO   
364547    inflammatory bowel disease  MONDO_grouped   

                                                  tail_id  tail_type  \
364546                                               5101          2   
364547  9960_12845_33643_11471_12831_12875_12941_13153...          2   

        display_relation    relation  
364546                11  indication  
364547                11  indication

### Drug --> contraindication --> Disease

In [69]:
disease_drug_triplets = triplets[((triplets.head_type==6) & (triplets.tail_type==2) & (triplets.relation == 'contraindication'))]
disease_drug_triplets.head()

head_index           head_name head_source  head_id  head_type  \
338348       15193          Rotigotine    DrugBank  DB05271          6   
338349       15193          Rotigotine    DrugBank  DB05271          6   
338352       14483  Estradiol valerate    DrugBank  DB13956          6   
338353       14483  Estradiol valerate    DrugBank  DB13956          6   
338354       16476     Phenazopyridine    DrugBank  DB01438          6   

        tail_index              tail_name    tail_source  \
338348       33577  hypertensive disorder          MONDO   
338349       36035           hypertension  MONDO_grouped   
338352       33577  hypertensive disorder          MONDO   
338353       36035           hypertension  MONDO_grouped   
338354       33577  hypertensive disorder          MONDO   

                            tail_id  tail_type  display_relation  \
338348                         5044          2                 8   
338349  1200_1134_15512_5080_100078          2                 8   
338352                         5044          2                 8   
338353  1200_1134_15512_5080_100078          2                 8   
338354                         5044          2                 8   

                relation  
338348  contraindication  
338349  contraindication  
338352  contraindication  
338353  contraindication  
338354  contraindication

In [70]:
x = torch.tensor(node_embeddings[20377]).unsqueeze(0)
x_transformed = transformation(model, x, 6, 2, 11)

In [71]:
disease_as_tail_embeddings = torch.tensor([node_embeddings[i] for i in disease_drug_triplets.tail_index.unique()])
disease_as_tail_embeddings = project(model, disease_as_tail_embeddings, 2)
disease_as_tail_embeddings

tensor([[ 0.0409,  0.0292, -0.0421,  ...,  0.0431,  0.0146, -0.0288],
        [ 0.0611,  0.0414, -0.0743,  ...,  0.0438,  0.0159,  0.0148],
        [ 0.0391,  0.0119, -0.0164,  ...,  0.0404, -0.0121, -0.0239],
        ...,
        [-0.0599, -0.0262, -0.0585,  ..., -0.0386, -0.1117, -0.0371],
        [ 0.0305,  0.1019, -0.0703,  ...,  0.1123,  0.0256,  0.0380],
        [ 0.0706, -0.0381,  0.0131,  ...,  0.0241,  0.0096,  0.0194]],
       device='cuda:0')

In [72]:
sim_scores = torch.nn.CosineSimilarity(dim=-1)(x_transformed.cpu(), disease_as_tail_embeddings.cpu())
sim_scores


tensor([ 0.1958,  0.1446,  0.0692,  ..., -0.1085,  0.1501,  0.1509])

In [73]:
disease_drug_triplets[(disease_drug_triplets.head_index == 20377)]

head_index         head_name head_source  head_id  head_type  \
340948       20377  Benzoyl peroxide    DrugBank  DB09096          6   
340949       20377  Benzoyl peroxide    DrugBank  DB09096          6   
340962       20377  Benzoyl peroxide    DrugBank  DB09096          6   
340963       20377  Benzoyl peroxide    DrugBank  DB09096          6   
342047       20377  Benzoyl peroxide    DrugBank  DB09096          6   
342048       20377  Benzoyl peroxide    DrugBank  DB09096          6   
346162       20377  Benzoyl peroxide    DrugBank  DB09096          6   
346163       20377  Benzoyl peroxide    DrugBank  DB09096          6   
346644       20377  Benzoyl peroxide    DrugBank  DB09096          6   
346645       20377  Benzoyl peroxide    DrugBank  DB09096          6   
346646       20377  Benzoyl peroxide    DrugBank  DB09096          6   
348974       20377  Benzoyl peroxide    DrugBank  DB09096          6   
350099       20377  Benzoyl peroxide    DrugBank  DB09096          6   
350100       20377  Benzoyl peroxide    DrugBank  DB09096          6   
359267       20377  Benzoyl peroxide    DrugBank  DB09096          6   
359268       20377  Benzoyl peroxide    DrugBank  DB09096          6   
361053       20377  Benzoyl peroxide    DrugBank  DB09096          6   
364539       20377  Benzoyl peroxide    DrugBank  DB09096          6   
366542       20377  Benzoyl peroxide    DrugBank  DB09096          6   
366599       20377  Benzoyl peroxide    DrugBank  DB09096          6   
366600       20377  Benzoyl peroxide    DrugBank  DB09096          6   
366601       20377  Benzoyl peroxide    DrugBank  DB09096          6   
366695       20377  Benzoyl peroxide    DrugBank  DB09096          6   
366696       20377  Benzoyl peroxide    DrugBank  DB09096          6   
366697       20377  Benzoyl peroxide    DrugBank  DB09096          6   

        tail_index                                  tail_name    tail_source  \
340948       28756                   photoparoxysmal response  MONDO_grouped   
340949       37762                   photosensitivity disease          MONDO   
340962       39774  anogenital human papillomavirus infection          MONDO   
340963       83754                                common wart          MONDO   
342047       35764                             kidney disease          MONDO   
342048       83762                                  pyoureter          MONDO   
346162       38666               adrenocortical insufficiency          MONDO   
346163       30813                            Addison disease          MONDO   
346644       37784                              Crohn disease  MONDO_grouped   
346645       28158                 inflammatory bowel disease  MONDO_grouped   
346646       83770                            Crohn's colitis          MONDO   
348974       83782                     exfoliative dermatitis          MONDO   
350099       33575                diabetes mellitus (disease)          MONDO   
350100       29113                      diabetic ketoacidosis          MONDO   
359267       83827              Clostridium difficile colitis          MONDO   
359268       83828        perinatal necrotizing enterocolitis          MONDO   
361053       36924                                 dermatitis          MONDO   
364539       37785               ulcerative colitis (disease)          MONDO   
366542       83881                               skin atrophy          MONDO   
366599       39511                             telangiectasis          MONDO   
366600       36451                          capillary disease          MONDO   
366601       32980      hereditary hemorrhagic telangiectasia          MONDO   
366695       35931                peripheral vascular disease          MONDO   
366696       83883         intermittent vascular claudication          MONDO   
366697       39798                peripheral arterial disease          MONDO   

                                                  tail

In [74]:
k_nodes = 10
sim_sorted = disease_drug_triplets.tail_index.unique()[torch.argsort(sim_scores, descending=True)[:k_nodes]]
df_ = pd.DataFrame({
    "node_index": sim_sorted
})
df_ = df_.merge(biobridge_data.get_primekg().get_nodes(), on="node_index")
df_

node_index                               node_name    node_source  \
0       29709                      dermatitis, atopic          MONDO   
1       36924                              dermatitis          MONDO   
2       37770                      contact dermatitis          MONDO   
3       36129                           atopic eczema          MONDO   
4       33651                   seborrheic dermatitis  MONDO_grouped   
5       83777                 occupational dermatitis          MONDO   
6       83782                  exfoliative dermatitis          MONDO   
7       36644                            skin disease          MONDO   
8       33534  pediatric systemic lupus erythematosus          MONDO   
9       31850                    seborrheic keratosis          MONDO   

     node_id node_type  
0      11292   disease  
1       2406   disease  
2       5480   disease  
3       4980   disease  
4  6608_6609   disease  
5       6589   disease  
6      43233   disease  
7       5093   disease  
8      19725   disease  
9       8420   disease

In [75]:
disease_drug_triplets[(disease_drug_triplets.head_index == 20377) & (disease_drug_triplets.tail_index.isin(df_.node_index))]

head_index         head_name head_source  head_id  head_type  \
348974       20377  Benzoyl peroxide    DrugBank  DB09096          6   
361053       20377  Benzoyl peroxide    DrugBank  DB09096          6   

        tail_index               tail_name tail_source tail_id  tail_type  \
348974       83782  exfoliative dermatitis       MONDO   43233          2   
361053       36924              dermatitis       MONDO    2406          2   

        display_relation          relation  
348974                 8  contraindication  
361053                 8  contraindication